language: go
go: 
  - 1.1
  - 1.2
  - 1.3
  - tip
notificaitons:
  email:
    recipients:
      jason.mcvetta@gmail.com
    on_success: change
    on_failure: always
before_script:
  - go get -v github.com/bmizerany/assert
  - go get -v github.com/jmcvetta/randutil
#
# Lines below copied from # https://github.com/versae/neo4j-rest-client/blob/master/.travis.yml
#
before_install:
  - sh start-neo4j.sh

env:
  - NEO4J_VERSION="2.1.2"
