language: go
go: 
  - 1.3
  
env:
  - NEO_VERSION="2.1.3"

before_script:
  - go get gopkg.in/check.v1
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  
after_success:
  - tail -n +2 typescov.out >> bench.out
  - tail -n +2 cov.out >> bench.out
  - goveralls -coverprofile=bench.out 
  
before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - echo "org.neo4j.server.transaction.timeout=1" >> neo4j-community-$NEO_VERSION/conf/neo4j-server.properties
  - neo4j-community-$NEO_VERSION/bin/neo4j start

install:
  - cd ../../..
  - mkdir gopkg.in
  - mv github.com/go-cq/cq gopkg.in/cq.v1
  - cd gopkg.in/cq.v1

script:
  - cd types
  - go test -covermode=count -coverprofile=../typescov.out
  - cd ..
  - go test -covermode=count -coverprofile=cov.out
  - go test -check.b -covermode=count -coverprofile=bench.out
